# Generated by Django 4.2.5 on 2023-09-28 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Doctor",),
    ]
